service: lambexpress
app: test-api
#org: your-org-name

plugins:
  - serverless-offline

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'  	
# functions:
#   app:
#     handler: index.handler
#     events:
#       - http: ANY /
#       - http: 'ANY {proxy+}'